name: diary_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.0.2
  logging: ^1.1.0
  image_picker: ^0.8.4+4
  file_picker: ^5.1.1  # Added file_picker for web support

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
 
  assets:
  - .env

